version: "3.5"

services:
  reverse-proxy:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./reverse-proxy/sites.conf:/etc/nginx/conf.d/default.conf

  phpbuilder:
    image: gazrogers/phpapp-dev:7.4-4.0.6-1
    volumes:
      - ../:/var/www/html/

  mnmlsm-backend:
    image: gazrogers/phpapp-dev:7.4-4.0.6-1
    volumes:
      - ../mnmlsm-backend:/var/www/html/
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PREFIX: ${DB_PREFIX}

  redis:
    image: redis:6.0.8
    volumes:
      - ./volumes/redis-data:/data

  db:
    image: mysql:5.7.31
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_520_ci
    volumes:
      - ./volumes/test-db-data/:/var/lib/mysql
      - ./database-setup/:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: Europe/London

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:80"
